KWARGS_DATA = "data"
KWARGS_BROWSER = "browser"
KWARGS_API_SESSION = "api"
KWARGS_TESTCASETYPE = "TESTCASETYPE"
KWARGS_TESTRUNATTRIBUTES = "TESTRUNEXECUTIONPARAMETERS"
KWARGS_TESTRUNINSTANCE = "TESTRUNINSTANCE"
KWARGS_TIMING = "TimingClassInstance"

CLASSES_TESTCASESEQUENCE = "TestCaseSequence.TestCaseSequenceMaster.TestCaseSequenceMaster"
CLASSES_TESTCASE = "TestCase.TestCaseMaster.TestCaseMaster"

TIMING_END = "end"
TIMING_START = "start"
TIMING_TESTRUN = "Complete Testrun"
TIMING_DURATION = "Dauer"
TIMESTAMP = "timestamp"
TIMELOG = "timelog"

BROWSER_FIREFOX = "FF"
BROWSER_CHROME = "CHROME"
BROWSER_SAFARI = "SAFARI"
BROWSER_REMOTE = 'REMOTE'
BROWSER_MODE_HEADLESS = "HEADLESS"

CMD_CLICK = "CLICK"
CMD_SETTEXT = "SETTEXT"
CMD_FORCETEXT = "FORCETEXT"

TESTCASESTATUS = "TestCaseStatus"
TESTCASESTATUS_SUCCESS = "OK"
TESTCASESTATUS_ERROR = "Failed"

DATABASE_FROM_LINE = "FROM_LINE"
DATABASE_TO_LINE = "TO_LINE"

STRUCTURE_TESTCASESEQUENCE = "TESTSEQUENCE"
STRUCTURE_TESTCASE = "TESTCASE"
STRUCTURE_TESTSTEP = "TESTSTEP"

EXECUTION_PARALLEL = "PARALLEL_RUNS"