# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 480)
        MainWindow.setStyleSheet("selection-background-color: rgb(246, 194, 152);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 91, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pathLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout_2.addWidget(self.pathLabel)
        self.testrunLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.testrunLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testrunLabel.setObjectName("testrunLabel")
        self.verticalLayout_2.addWidget(self.testrunLabel)
        self.settingsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.settingsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.settingsLabel.setObjectName("settingsLabel")
        self.verticalLayout_2.addWidget(self.settingsLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 60, 261, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pathLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.verticalLayout_3.addWidget(self.pathLineEdit)
        self.testrunComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.testrunComboBox.setObjectName("testrunComboBox")
        self.verticalLayout_3.addWidget(self.testrunComboBox)
        self.settingsComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.settingsComboBox.setObjectName("settingsComboBox")
        self.verticalLayout_3.addWidget(self.settingsComboBox)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(410, 60, 101, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.browsePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.browsePushButton.setObjectName("browsePushButton")
        self.verticalLayout_4.addWidget(self.browsePushButton)
        self.executePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.executePushButton.setObjectName("executePushButton")
        self.verticalLayout_4.addWidget(self.executePushButton)
        self.detailPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.detailPushButton.setObjectName("detailPushButton")
        self.verticalLayout_4.addWidget(self.detailPushButton)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 60, 411, 171))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 25))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPreferences = QtWidgets.QMenu(self.menuFile)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuKatalon_Importer = QtWidgets.QMenu(self.menuImport)
        self.menuKatalon_Importer.setObjectName("menuKatalon_Importer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsettings = QtWidgets.QAction(MainWindow)
        self.actionsettings.setObjectName("actionsettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy_Ctrl_C = QtWidgets.QAction(MainWindow)
        self.actionCopy_Ctrl_C.setObjectName("actionCopy_Ctrl_C")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuPreferences.addAction(self.actionsettings)
        self.menuFile.addAction(self.menuPreferences.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuKatalon_Importer.addAction(self.actionCopy_Ctrl_C)
        self.menuKatalon_Importer.addAction(self.actionPaste)
        self.menuKatalon_Importer.addAction(self.actionSave)
        self.menuImport.addAction(self.menuKatalon_Importer.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.pathLabel.setBuddy(self.pathLineEdit)
        self.testrunLabel.setBuddy(self.testrunComboBox)
        self.settingsLabel.setBuddy(self.settingsComboBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.browsePushButton, self.testrunComboBox)
        MainWindow.setTabOrder(self.testrunComboBox, self.settingsComboBox)
        MainWindow.setTabOrder(self.settingsComboBox, self.detailPushButton)
        MainWindow.setTabOrder(self.detailPushButton, self.executePushButton)
        MainWindow.setTabOrder(self.executePushButton, self.pathLineEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pathLabel.setText(_translate("MainWindow", "Path"))
        self.testrunLabel.setText(_translate("MainWindow", "Test Run"))
        self.settingsLabel.setText(_translate("MainWindow", "Settings"))
        self.browsePushButton.setText(_translate("MainWindow", "Browse"))
        self.executePushButton.setText(_translate("MainWindow", "Execute"))
        self.detailPushButton.setText(_translate("MainWindow", "Details"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img width=\"400\" src=\":/new/logo/baangtLogo\"/></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuKatalon_Importer.setTitle(_translate("MainWindow", "Katalon Importer"))
        self.actionsettings.setText(_translate("MainWindow", "settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCopy_Ctrl_C.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

