"""empty message

Revision ID: 17cfc1a6b077
Revises: c7fc082b1d55
Create Date: 2020-02-16 18:15:26.010971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cfc1a6b077'
down_revision = 'c7fc082b1d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teststep_executions', 'optional',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teststep_executions', 'optional',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
