"""empty message

Revision ID: c7fc082b1d55
Revises: afb044a83b98
Create Date: 2020-02-06 13:40:37.665770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fc082b1d55'
down_revision = 'afb044a83b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teststep_executions', sa.Column('comparision', sa.String(), nullable=True))
    op.add_column('teststep_executions', sa.Column('locator', sa.String(), nullable=True))
    op.add_column('teststep_executions', sa.Column('optional', sa.Boolean(), nullable=True))
    op.add_column('teststep_executions', sa.Column('release', sa.String(), nullable=True))
    op.add_column('teststep_executions', sa.Column('timeout', sa.Float(precision='5,2'), nullable=True))
    op.add_column('teststep_executions', sa.Column('value', sa.String(), nullable=True))
    op.add_column('teststep_executions', sa.Column('value2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teststep_executions', 'value2')
    op.drop_column('teststep_executions', 'value')
    op.drop_column('teststep_executions', 'timeout')
    op.drop_column('teststep_executions', 'release')
    op.drop_column('teststep_executions', 'optional')
    op.drop_column('teststep_executions', 'locator')
    op.drop_column('teststep_executions', 'comparision')
    # ### end Alembic commands ###
